#!/usr/bin/env bash
# Configure HAproxy to automatically redirect HTTP traffic to HTTPS.
# Global settings
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

# Default SSL material locations
ca-base /etc/ssl/certs
crt-base /etc/ssl/private

# Default ciphers to use on SSL-enabled listening sockets.
# For more information, see ciphers(1SSL).
ssl-default-bind-ciphers kEECDH+aRSA+AES:kRSA+AES:+AES256:RC4-SHA:!kEDH:!LOW:!EXP:!MD5:!aNULL:!eNULL

# Default certificate to use for SSL-enabled listening sockets.
# For more information, see ssl(8).
ssl-default-bind-options no-sslv3

# Frontend configuration for HTTP to HTTPS redirection
frontend http-in
    bind *:80
    http-request redirect location https://%[hdr(host)]%[capture.req.uri] code 301 if !{ ssl_fc }

