#!/usr/bin/env bash
# Configure HAproxy to automatically redirect HTTP traffic to HTTPS.
global
    maxconn 4096
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    http-request redirect location https://%[hdr(host)]%[capture.req.uri] code 301 if !{ ssl_fc }

frontend https-in
    bind *:443 ssl crt /etc/ssl/certs/www.yourdomain.com.pem
    
    default_backend www-backend

backend www-backend
	balance roundrobin
        server 496-web-01 35.243.204.105:80
        server 496-web-02 35.190.182.239:80

backend le-certbot-backend
	server letsencrypt 127.0.0.1:8888
