#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
echo "server {
    listen 80;
    server_name _;
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}" > /etc/nginx/sites-available/redirect_me

ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/redirect_me

nginx -t

service nginx restart
