#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
service nginx start
mkdir /etc/nginx/html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
echo "error_page 404 /404.html;
location = /404.html{
	root /etc/nginx/html; 
	internal;
}" > /etc/nginx/sites-available/default
nginx -t
service nginx restart
