#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Install HAProxy if not already installed
if ! command -v haproxy &> /dev/null
then
    sudo apt-get -y update
    sudo apt-get -y install haproxy=1.6.\*
fi

# Configure HAProxy to send traffic to web-01 and web-02 using round-robin algorithm
echo '
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
'
>> etc/haproxy/haproxy.cfg > /dev/null <<EOT

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
