#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Install HAProxy if not already installed
if ! command -v haproxy &> /dev/null
then
    sudo apt update
    sudo apt install haproxy -y
fi

# Configure HAProxy to send traffic to web-01 and web-02 using round-robin algorithm
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOT

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
