#!/usr/bin/env bash
# Define a signal handler function
stop_process() {
    echo "Terminated"
    exit 0
}

# Register the signal handler function
trap stop_process SIGUSR1

# Infinite loop to display "To infinity and beyond"
while true; do
    echo "To infinity and beyond"
    sleep 1
done
