#!/usr/bin/env bash
 Find the PID of the "7-highlander" process
PID=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$PID" ]; then
    # Send a SIGTERM signal to the process
    kill -s SIGTERM "$PID"
else
    echo "Process not found"
fi
