#!/usr/bin/env bash

# This script displays the content of the file /etc/passwd

# Set the IFS (Internal Field Separator) to ":" to parse the fields in /etc/passwd
IFS=":"

# Read the file /etc/passwd line by line using a while loop
while IFS=: read -r username _ userid _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
