#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username _ userid groupid _ homedir shell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
    echo "User $userid's place is protected by the passcode PASSWORD."
    echo "More info about the user here: USER ID INFO"
done < /etc/passwd
