#!/usr/bin/env bash
# This Bash script configures an Ubuntu server.
set -e

# Check if script is running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Modify /etc/hosts file
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sed -i 's/8.8.8.8/157.240.11.35/g' /etc/hosts
